In [1]:
import jieba
import pandas as pd
import sklearn
import numpy as np

In [2]:
data = pd.read_csv("../data/atec_nlp_sim_train.csv", encoding="utf-8", delimiter="\t", header=None)

In [3]:
data_add = pd.read_csv("../data/atec_nlp_sim_train_add.csv", encoding="utf-8", delimiter="\t", header=None)

In [4]:
print(data_add.shape)
data_add.head(2)

(63131, 4)


0                 1                      2  3
0  1  为何我无法申请开通花呗信用卡收款  支付宝开通信用卡花呗收款不符合条件怎么回事  1
1  2      花呗分期付款会影响使用吗             花呗分期有什么影响吗  0

In [5]:
print(data.shape)
data.head(2)

(39346, 4)


0                1                               2  3
0  1      怎么更改花呗手机号码  我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号  1
1   2  也开不了花呗，就这样了？完事了                      真的嘛？就是花呗付款  0

In [6]:
data = pd.concat([data, data_add])

print(data.shape)
data.head(2)

(102477, 4)


0                1                               2  3
0  1      怎么更改花呗手机号码  我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号  1
1   2  也开不了花呗，就这样了？完事了                      真的嘛？就是花呗付款  0

In [7]:
data.columns = ["sent_id", "sent_1", "sent_2", "label"]
data = data[["sent_1", "sent_2", "label"]]

In [8]:
data.index = list(range(data.shape[0]))

In [9]:
data.to_csv("../data/sim_train.csv", sep="\t")

In [10]:
data.head(2)

sent_1                          sent_2  label
0      怎么更改花呗手机号码  我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号      1
1  也开不了花呗，就这样了？完事了                      真的嘛？就是花呗付款      0

In [11]:
positive_data = data[data["label"] == 1]

print(positive_data.shape)
positive_data.head(20)

(18685, 3)


sent_1  \
0                  怎么更改花呗手机号码   
15                 花呗的安全没有验证成功   
17                 借呗还款了，额度未恢复   
21                   闲鱼可以使用花呗吗   
24                   花呗更改绑定银行卡   
31                    花呗***期免息   
33               开通花呗不用的话会有费用吗   
41                 我蚂蚁借呗放款没有到账   
47                   花呗怎么付款不鸟了   
57             支付宝花呗分期还款怎么提前还清   
58     注销了一个花呗账号，新账号是否还能再开通花呗了   
61                 为何蚂蚁借呗不能使用了   
63          用了这么久的支付宝也不给开通借呗，哼   
66               蚂蚁借呗的额度为什么会下降   
73   我***月份花呗消费是***元，怎么要我还***元   
87                    怎么花呗不能支付   
99               花呗支付可以使用购物津贴吗   
101             为什么每个人的借呗日息不一样   
108                  怎么开通，花呗收款   
109             我的花呗怎么用这用这不让用了   

                                                sent_2  label  
0                       我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号      1  
15                                       花呗安全验证没通过怎么回事      1  
17                                    借呗还款后额度没有恢复还显示借款      1  
21                                        花呗可以在闲鱼上面交易吗      1  
24                                         如何更换花呗绑定银行卡      1  
31                                      蚂蚁花呗***期免息什么意思      1  
33                                      开通花呗不用，会不会产生费用      1  
41                                         借呗还款为什么没有到帐      1  
47                                       帮忙看一下我花呗怎么用不了      1  
57                                   蚂蚁花呗分期付款可以全部提前还款吗      1  
58                                 把以前的帐号注销，现在这个能开通花呗吗      1  
61                                我的借呗***年能有***年怎么不能用了      1  
63                                  我用支付宝三四年了也不见给我开通借呗      1  
66                                  为什么借呗额度被降低了，没有不良记录      1  
73   我原本这个月总的花呗需要还***元，我还了一次***，又还了一个***，剩余的应该是***，...      1  
87                                          花呗付款不了怎么回事      1  
99                                     使用购物津贴的费用可以用花呗吗      1  
101                                      为什么借呗利息有的高有的底      1  
108                                        怎么注册可以花呗收钱的      1  
109                                         我花呗为什么不能用了      1

In [12]:
negtive_data = data[data["label"] == 0]

print(negtive_data.shape)
negtive_data.head(20)

(83792, 3)


sent_1                     sent_2  label
1          也开不了花呗，就这样了？完事了                 真的嘛？就是花呗付款      0
2              花呗冻结以后还能开通吗              我的条件可以开通花呗借款吗      0
3                 如何得知关闭借呗                    想永久关闭借呗      0
4                   花呗扫码付钱                二维码扫描可以用花呗吗      0
5               花呗逾期后不能分期吗     我这个 逾期后还完了 最低还款 后 能分期吗      0
6                   花呗分期清空                     花呗分期查询      0
7                 借呗逾期短信通知                 如何购买花呗短信通知      0
8         借呗即将到期要还的账单还能分期吗                  借呗要分期还，是吗      0
9            花呗为什么不能支付手机交易            花呗透支了为什么不可以继续用了      0
10         在吗，双***有临时花呗额度吗               花呗临时额度到时间怎么办      0
11              我什么时候开通了花呗                查我什么时候用过，花呗      0
12  花呗每月还了最低还款后还会有万分之五的利息吗               花呗每个月最低还款怎么算      0
13            我想用蚂蚁借呗怎么用不了  蚂蚁借呗设置了一次性还款，现在想分期还款，怎么操作      0
14                 花呗也不能用了                      花呗没用过      0
16                 我开通不了借呗                     我要申请借呗      0
18     就是我花呗忘记还款了。逾期一天。有事吗            花呗账单在到期当天还款是逾期吗      0
19             我问你我借呗怎么要还钱                 怎么一次性还蚂蚁借呗      0
20             是否有花呗就不可以借呗                不实用花呗就没有借呗吗      0
22                花呗可以买手机吗                  花呗逾期一天可以么      0
23                借呗每月还款时间                    借呗多少天还款      0

In [14]:
jieba.load_userdict("../data/dict")

seg_list = jieba.cut(" 花呗可以付滴车费吗")
print("Full Mode: " + "/ ".join(seg_list))  # 全模式

seg_list = jieba.cut(" 花呗可以付滴车费吗", HMM=False)
print("Default Mode: " + "/ ".join(seg_list))  # 精确模式

seg_list = jieba.cut("想要网商贷能不能切换回借呗")  # 默认是精确模式
print(", ".join(seg_list))

seg_list = jieba.cut_for_search("我问你我借呗怎么要还钱")  # 搜索引擎模式
print(", ".join(seg_list))

Full Mode:  / 花呗/ 可以/ 付滴/ 车费/ 吗
Default Mode:  / 花呗/ 可以/ 付/ 滴/ 车费/ 吗
想要, 网商贷, 能, 不能, 切换, 回, 借呗
我, 问, 你, 我, 借呗, 怎么, 要, 还, 钱


In [15]:
data["sent_1_seg"] = data["sent_1"].apply(lambda x: " ".join(jieba.cut(x, HMM=False)))
data["sent_2_seg"] = data["sent_2"].apply(lambda x: " ".join(jieba.cut(x, HMM=False)))

In [16]:
data.to_csv("../data/sim_train_seg.csv", sep="\t")

data.head(2)

sent_1                          sent_2  label  \
0      怎么更改花呗手机号码  我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号      1   
1  也开不了花呗，就这样了？完事了                      真的嘛？就是花呗付款      0   

                  sent_1_seg                                      sent_2_seg  
0             怎么 更改 花呗 手机号码  我 的 花呗 是 以前 的 手机号码 ， 怎么 更 改成 现在 的 支付宝 的 号码 手机号  
1  也 开 不了 花呗 ， 就 这样 了 ？ 完事 了                                 真的 嘛 ？ 就是 花呗 付款

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

def my_tokenizer(x):
    return x.split()

vectorizer = CountVectorizer(tokenizer=my_tokenizer) 
# Document-term matrix.

In [18]:

analyze = vectorizer.build_analyzer()

print(analyze("也 开 不了 花呗 ， 就 这样 了 ？ 完事 了"))

analyze("也 开 不了 花呗 ， 就 这样 了 ？ 完事 了") == (
     ['也', '开', '不了', '花呗', '，', '就', '这样', '了', '？', '完事', '了'])

['也', '开', '不了', '花呗', '，', '就', '这样', '了', '？', '完事', '了']


True

In [19]:
corpus = list(data["sent_1_seg"].values)
print("-----the number of sent_1_seg------", len(corpus))
corpus.extend(list(data["sent_2_seg"].values))
print("-----the number of last corpus------", len(corpus))

-----the number of sent_1_seg------ 102477
-----the number of last corpus------ 204954


In [20]:
corpus[1]

'也 开 不了 花呗 ， 就 这样 了 ？ 完事 了'

In [21]:
corpus_matrix = vectorizer.fit_transform(corpus)

In [212]:
print("===the len of dictionary is====", len(list(vectorizer.vocabulary_.keys())))

with open("../data/words.txt", "w") as writer:
    for word, index in vectorizer.vocabulary_.items():
        writer.write("%s\t%d\n" %(word, index))

===the len of dictionary is==== 8280


In [22]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=False)
corpus_tfidf = transformer.fit_transform(corpus_matrix)

In [23]:
import pickle
pickle.dump(vectorizer, open("../data/countvector.model", "wb"), 2)
pickle.dump(transformer, open("../data/tfidf.model", "wb"), 2)

In [25]:
corpus_tfidf_matrix = corpus_tfidf.toarray()

In [26]:
corpus_tfidf_matrix[0,:]

array([0., 0., 0., ..., 0., 0., 0.])

In [27]:
corpus_score = []

from scipy.spatial.distance import cosine

for index in range(corpus_tfidf_matrix.shape[0] // 2):
    score = 1 - cosine (corpus_tfidf_matrix[index], corpus_tfidf_matrix[corpus_tfidf_matrix.shape[0] // 2 + index])
    corpus_score.append(score)

In [28]:
print(len(corpus_score))
print(corpus_score[:10])

102477
[0.15334329980866712, 0.13322662171379718, 0.1872843522270653, 0.17168763823140454, 0.013332056817290883, 0.5879051425805042, 0.17251931340717375, 0.6766118490967401, 0.42480684356656706, 0.08149166976468991]


In [29]:
s = np.array([1, 2, 3, 4])
s = s > 3
s.astype(int)

array([0, 0, 0, 1])

In [49]:
corpus_score_ = np.array(corpus_score)
corpus_score_ = corpus_score_ > 0.8
predicted = corpus_score_.astype(int)
predicted

array([0, 0, 0, ..., 0, 0, 0])

In [50]:
print(len(predicted[predicted == 1]))
predicted[predicted == 1]

1553


array([1, 1, 1, ..., 1, 1, 1])

In [51]:
label = data["label"].values

In [52]:
import sklearn.metrics
print(sklearn.metrics.classification_report(label, predicted))

             precision    recall  f1-score   support

          0       0.82      0.99      0.90     83792
          1       0.55      0.05      0.08     18685

avg / total       0.77      0.82      0.75    102477



In [37]:
data["sim_score"] = corpus_score
data.head(10)

sent_1                          sent_2  label  \
0       怎么更改花呗手机号码  我的花呗是以前的手机号码，怎么更改成现在的支付宝的号码手机号      1   
1   也开不了花呗，就这样了？完事了                      真的嘛？就是花呗付款      0   
2       花呗冻结以后还能开通吗                   我的条件可以开通花呗借款吗      0   
3          如何得知关闭借呗                         想永久关闭借呗      0   
4            花呗扫码付钱                     二维码扫描可以用花呗吗      0   
5        花呗逾期后不能分期吗          我这个 逾期后还完了 最低还款 后 能分期吗      0   
6            花呗分期清空                          花呗分期查询      0   
7          借呗逾期短信通知                      如何购买花呗短信通知      0   
8  借呗即将到期要还的账单还能分期吗                       借呗要分期还，是吗      0   
9     花呗为什么不能支付手机交易                 花呗透支了为什么不可以继续用了      0   

                   sent_1_seg                                      sent_2_seg  \
0              怎么 更改 花呗 手机号码  我 的 花呗 是 以前 的 手机号码 ， 怎么 更 改成 现在 的 支付宝 的 号码 手机号   
1   也 开 不了 花呗 ， 就 这样 了 ？ 完事 了                                 真的 嘛 ？ 就是 花呗 付款   
2           花呗 冻结 以后 还 能 开通 吗                            我 的 条件 可以 开通 花呗 借款 吗   
3                 如何 得知 关闭 借呗                                      想 永久 关闭 借呗   
4                   花呗 扫 码 付钱                                二维码 扫描 可以 用 花呗 吗   
5             花呗 逾期 后 不能 分期 吗          我 这个   逾期 后 还 完 了   最低 还款   后   能 分期 吗   
6                    花呗 分期 清空                                        花呗 分期 查询   
7                 借呗 逾期 短信 通知                                  如何 购买 花呗 短信 通知   
8  借呗 即将 到期 要 还 的 账单 还 能 分期 吗                                 借呗 要 分期 还 ， 是 吗   
9          花呗 为什么 不能 支付 手机 交易                         花呗 透支 了 为什么 不 可以 继续 用 了   

   sim_score  
0   0.153343  
1   0.133227  
2   0.187284  
3   0.171688  
4   0.013332  
5   0.587905  
6   0.172519  
7   0.676612  
8   0.424807  
9   0.081492

In [55]:
data.loc[lambda x: (x.sim_score >= 0.5) & (x.label == 0), :].sort_values(by="sim_score", ascending=False)

sent_1  \
69590   支付宝*******花呗今天将从余额、储蓄卡或余额宝自动还***元，可登录支付宝-花呗核对，...   
5947                                               花呗分期退款   
19700                        您是可以进入支付宝——花呗——我的账单——截图给小二一下   
61568                                           怎么为好友花呗加分   
87355                                            花呗借呗取消授权   
58929                                          网商银行 就是花呗吗   
69862                                    好友怎么样才能为我的花呗额度加分   
59806                                        别人可以帮我还借呗的款吗   
83514                                            借呗支持哪个银行   
22727                                            怎么实名认证花呗   
83055                                            怎么变成商家收款   
71031                                      蚂蚁借呗跟网商银行有什么区别   
50496                                             花呗额度有效期   
35162                                              永久关闭借呗   
86056                                       花呗怎么只有***的可用度   
31114                                            查询还款借呗记录   
4712                                           进不去花呗是怎么回事   
56785                                  ***月***号用花呗 什么时候还款   
72076                                     花呗临时额度可以账单分期还款吗   
62164   ***月份花呗账单，指的是***月***日出的账单，入账时间是***月******日的，不是...   
90895                                          港澳居民用不了花呗吗   
40085                                          借呗可以转入余额宝吗   
66163                                            花呗还款了未显示   
15318                                         借呗可以设置手势密码吗   
3474                                           花呗分期***期免息   
101884                                  花呗***元，分***期利息多少钱   
56701                               为什么借呗 只有***个月和***个月期限   
88312                                     花呗全民摇一摇临时额度是真的吗   
16444                                       建设银行支持蚂蚁借呗还款吗   
81407                                               花呗买车险   
...                                                   ...   
19037                                        花呗逾期一天记录什么消除   
34778                                         在淘宝里怎么用花呗的钱   
65402                                         为什么合并付款不能花呗   
30446                                         花呗能不能不发短信通知   
38983                                     我蚂蚁借呗逾期了.会影响信用吗   
20187                                   身份信息完善了，为什么还不可以借呗   
2050                                             我想借呗提升额度   
94484                                         花呗人脸识别不了为什么   
26829                                       蚂蚁花呗分了期还可以在分嘛   
50327                                        蚂蚁借呗，当天可以还款吗   
89610                                       我的花呗额度怎么突然降低啦   
28582                                          一直有花呗支付服务费   
6001                                借呗还款我余额宝有钱为什么还从银行卡里扣费   
50851                                       花呗分期提前结清要手续费吗   
55731                       我***号付的款，商家说没收到，而我这边花呗已经付款成功了   
7853                                         如何切换另一个账号的花呗   
148                                              ***元花呗立减   
41329                                            我的三期花呗免息   
43638                                   花呗额度自己弄小了我想调回去***   
11364                                         借呗可更换银行卡还款吗   
21943                                    已开通信用卡花呗收款，但无法收款   
81818                                              借呗安全风险   
84446                          花呗这个月最低还款了，剩余那些没还的下个月可以分期吗   
93793                                   为什么我自己加的金额和花呗的不一样   
56453                                      淘宝店为什么开通不了花呗支付   
24484                                          借呗最高能分期几个月   
18629                                    为什么我是网商贷 别人是蚂蚁借呗   
75399                                          十号当天还能还花呗吗   
68063                     修改手机号码，会影响蚂蚁花呗和蚂蚁借呗的额度嘛，还有芝麻信用分   
33629                                             花呗有单笔限额   

                                                   sent_2  label  \
69590   支付宝*******花呗今天将从余额、储蓄卡或余额宝自动还***元，可登录支付宝-花呗核对，...      0   
5947                                              花呗分期 退款      0   
19700                    您是可以进入支付宝——花呗——我的账单——截图给小二一下，或者是      0

In [57]:
data.loc[lambda x: (x.sim_score < 0.5) & (x.label == 1), :].sort_values(by="sim_score", ascending=False).to_csv("../data/false_neg")